branch-protection:
  protect: true
  required_status_checks:
    strict: true
    contexts:
      - "test"
  enforce_admins: true
  required_pull_request_reviews:
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    required_approving_review_count: 1
  restrictions:
    apps: []
    users: []
    teams: []