---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-downloader
  labels:
    app: media-downloader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-downloader
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: media-downloader
    spec:
      containers:
        - name: media-downloader
          image: media-downloader:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DEBUG
              value: "false"
            - name: ENVIRONMENT
              value: "production"
            - name: PORT
              value: "8000"
            - name: HOST
              value: "0.0.0.0"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: { }

---
apiVersion: v1
kind: Service
metadata:
  name: media-downloader
  labels:
    app: media-downloader
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: media-downloader

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: media-downloader
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: media-downloader
  minReplicas: 2
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80