name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  discussions: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Generate Release Notes
        id: generate_notes
        run: |
          # Get the previous tag
          prev_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          # Generate changelog content
          if [ -z "$prev_tag" ]; then
            # If no previous tag exists, get all commits
            changes=$(git log --pretty=format:"- %s")
          else
            # Get commits between tags
            changes=$(git log --pretty=format:"- %s" ${prev_tag}..HEAD)
          fi
          
          # Create release notes content
          {
            echo "## Changes"
            echo "$changes"
            echo
            echo "## Docker Images"
            echo "The following Docker images have been published:"
            echo
            echo "- \`ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}\`"
            echo "- \`ghcr.io/${{ github.repository }}:latest\`"
            echo "- \`zuptalo/media-downloader:${{ steps.get_version.outputs.version }}\`"
            echo "- \`zuptalo/media-downloader:latest\`"
          } > release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.version }}
          body_path: release_notes.md
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          generate_release_notes: false